/**
 *
 * $Id$
 */
package com.github.kanafghan.welipse.joomlagen.validation;

import com.github.kanafghan.welipse.joomlagen.ExtensionType;
import com.github.kanafghan.welipse.joomlagen.JoomlaVersion;

import com.github.kanafghan.welipse.webdsl.Website;
import org.eclipse.emf.ecore.EPackage;

/**
 * A sample validator interface for {@link com.github.kanafghan.welipse.joomlagen.JoomlaGenModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JoomlaGenModelValidator {
	boolean validate();

	boolean validateExtensionType(ExtensionType value);
	boolean validateJoomlaVersion(JoomlaVersion value);
	boolean validateExtensionName(String value);
	boolean validateExtension(Website value);

	boolean validateDatamodel(EPackage value);

	boolean validateCSS(String value);
}
