/**
 */
package com.github.kanafghan.welipse.joomlagen.provider;

import com.github.kanafghan.welipse.joomlagen.util.JoomlaGenAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class JoomlaGenItemProviderAdapterFactory extends JoomlaGenAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public JoomlaGenItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.github.kanafghan.welipse.joomlagen.JoomlaGenModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoomlaGenModelItemProvider joomlaGenModelItemProvider;

	/**
	 * This creates an adapter for a {@link com.github.kanafghan.welipse.joomlagen.JoomlaGenModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoomlaGenModelAdapter() {
		if (joomlaGenModelItemProvider == null) {
			joomlaGenModelItemProvider = new JoomlaGenModelItemProvider(this);
		}

		return joomlaGenModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.github.kanafghan.welipse.joomlagen.GenPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GenPackageItemProvider genPackageItemProvider;

	/**
	 * This creates an adapter for a {@link com.github.kanafghan.welipse.joomlagen.GenPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGenPackageAdapter() {
		if (genPackageItemProvider == null) {
			genPackageItemProvider = new GenPackageItemProvider(this);
		}

		return genPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.github.kanafghan.welipse.joomlagen.GenClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GenClassItemProvider genClassItemProvider;

	/**
	 * This creates an adapter for a {@link com.github.kanafghan.welipse.joomlagen.GenClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGenClassAdapter() {
		if (genClassItemProvider == null) {
			genClassItemProvider = new GenClassItemProvider(this);
		}

		return genClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.github.kanafghan.welipse.joomlagen.GenAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GenAttributeItemProvider genAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link com.github.kanafghan.welipse.joomlagen.GenAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGenAttributeAdapter() {
		if (genAttributeItemProvider == null) {
			genAttributeItemProvider = new GenAttributeItemProvider(this);
		}

		return genAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.github.kanafghan.welipse.joomlagen.GenReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GenReferenceItemProvider genReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link com.github.kanafghan.welipse.joomlagen.GenReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGenReferenceAdapter() {
		if (genReferenceItemProvider == null) {
			genReferenceItemProvider = new GenReferenceItemProvider(this);
		}

		return genReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.github.kanafghan.welipse.joomlagen.DatabaseTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatabaseTableItemProvider databaseTableItemProvider;

	/**
	 * This creates an adapter for a {@link com.github.kanafghan.welipse.joomlagen.DatabaseTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatabaseTableAdapter() {
		if (databaseTableItemProvider == null) {
			databaseTableItemProvider = new DatabaseTableItemProvider(this);
		}

		return databaseTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.github.kanafghan.welipse.joomlagen.GenOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GenOperationItemProvider genOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.github.kanafghan.welipse.joomlagen.GenOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGenOperationAdapter() {
		if (genOperationItemProvider == null) {
			genOperationItemProvider = new GenOperationItemProvider(this);
		}

		return genOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.github.kanafghan.welipse.joomlagen.GenParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GenParameterItemProvider genParameterItemProvider;

	/**
	 * This creates an adapter for a {@link com.github.kanafghan.welipse.joomlagen.GenParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGenParameterAdapter() {
		if (genParameterItemProvider == null) {
			genParameterItemProvider = new GenParameterItemProvider(this);
		}

		return genParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.github.kanafghan.welipse.joomlagen.GenDataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GenDataTypeItemProvider genDataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.github.kanafghan.welipse.joomlagen.GenDataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGenDataTypeAdapter() {
		if (genDataTypeItemProvider == null) {
			genDataTypeItemProvider = new GenDataTypeItemProvider(this);
		}

		return genDataTypeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (joomlaGenModelItemProvider != null) joomlaGenModelItemProvider.dispose();
		if (genPackageItemProvider != null) genPackageItemProvider.dispose();
		if (genClassItemProvider != null) genClassItemProvider.dispose();
		if (genAttributeItemProvider != null) genAttributeItemProvider.dispose();
		if (genReferenceItemProvider != null) genReferenceItemProvider.dispose();
		if (databaseTableItemProvider != null) databaseTableItemProvider.dispose();
		if (genOperationItemProvider != null) genOperationItemProvider.dispose();
		if (genParameterItemProvider != null) genParameterItemProvider.dispose();
		if (genDataTypeItemProvider != null) genDataTypeItemProvider.dispose();
	}

}
