package com.github.kanafghan.welipse.webdsl.expressions;

public enum ExpressionVariableKind {
	TEXT_CONTENT,
	IMAGE_SOURCE,
	LIST_ITERATOR_VARIABLE,
	LIST_COLLECTION,
	EXTERNAL_LINK_TARGET,
	ACTUAL_PARAMETER_VALUE,
	INPUT_LABEL,
	INPUT_VALUE,
	SELECTION_LIST_OPTIONS,
	SUBMIT_PERFORMER,
	SUBMIT_VALIDATOR,
	PAGE_PARAMETER,
	PAGE_VARIABLE,
	PARAMETER,
	VARIABLE
}
