/**
 *
 * $Id$
 */
package com.github.kanafghan.welipse.webdsl.validation;

import com.github.kanafghan.welipse.webdsl.PageElement;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EOperation;

/**
 * A sample validator interface for {@link com.github.kanafghan.welipse.webdsl.List}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ListValidator {
	boolean validate();

	boolean validateItem(String value);
	boolean validateCollectionProvider(EOperation value);
	boolean validateType(EClass value);
	boolean validateContent(EList<PageElement> value);
}
