/**
 *
 * $Id$
 */
package com.github.kanafghan.welipse.webdsl.validation;

import com.github.kanafghan.welipse.webdsl.Page;

/**
 * A sample validator interface for {@link com.github.kanafghan.welipse.webdsl.PageElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PageElementValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validatePage(Page value);
}
