/**
 *
 * $Id$
 */
package com.github.kanafghan.welipse.webdsl.validation;

import com.github.kanafghan.welipse.webdsl.PageElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.github.kanafghan.welipse.webdsl.Page}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PageValidator {
	boolean validate();

	boolean validateElements(EList<PageElement> value);
	boolean validateName(String value);
}
